<?xml version="1.0" encoding="utf-8"?><Database Name="EngriskIsFun" Class="dbEngriskIsFunDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC7308;Initial Catalog=EngriskIsFun;Integrated Security=True" SettingsObjectName="EngriskIsFun.Properties.Settings" SettingsPropertyName="EngriskIsFunConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Definitions" Member="Definitions">
    <Type Name="Definition">
      <Column Name="DefinitionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PartOfSpeech" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Example" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="WordsMoreThan13_Definition" Member="WordsMoreThan13" ThisKey="WordID" OtherKey="WordID" Type="WordsMoreThan13" IsForeignKey="true" />
      <Association Name="WordsLessThan10_Definition" Member="WordsLessThan10" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan10" IsForeignKey="true" />
      <Association Name="WordsLessThan11_Definition" Member="WordsLessThan11" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan11" IsForeignKey="true" />
      <Association Name="WordsLessThan13_Definition" Member="WordsLessThan13" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan13" IsForeignKey="true" />
      <Association Name="WordsLessThan7_Definition" Member="WordsLessThan7" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan7" IsForeignKey="true" />
      <Association Name="WordsLessThan8_Definition" Member="WordsLessThan8" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan8" IsForeignKey="true" />
      <Association Name="WordsLessThan9_Definition" Member="WordsLessThan9" ThisKey="WordID" OtherKey="WordID" Type="WordsLessThan9" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WordsMoreThan13" Member="WordsMoreThan13s">
    <Type Name="WordsMoreThan13">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsMoreThan13_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.Phonetics" Member="Phonetics">
    <Type Name="Phonetic">
      <Column Name="PhoneticID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Audio" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan10" Member="WordsLessThan10s">
    <Type Name="WordsLessThan10">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan10_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan11" Member="WordsLessThan11s">
    <Type Name="WordsLessThan11">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan11_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan13" Member="WordsLessThan13s">
    <Type Name="WordsLessThan13">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan13_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan7" Member="WordsLessThan7s">
    <Type Name="WordsLessThan7">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan7_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan8" Member="WordsLessThan8s">
    <Type Name="WordsLessThan8">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan8_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
  <Table Name="dbo.WordsLessThan9" Member="WordsLessThan9s">
    <Type Name="WordsLessThan9">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="WordsLessThan9_Definition" Member="Definitions" ThisKey="WordID" OtherKey="WordID" Type="Definition" />
    </Type>
  </Table>
</Database>