#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngriskIsFun
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EngriskIsFun")]
	public partial class dbEngriskIsFunDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDefinition(Definition instance);
    partial void UpdateDefinition(Definition instance);
    partial void DeleteDefinition(Definition instance);
    partial void InsertWordsMoreThan13(WordsMoreThan13 instance);
    partial void UpdateWordsMoreThan13(WordsMoreThan13 instance);
    partial void DeleteWordsMoreThan13(WordsMoreThan13 instance);
    partial void InsertPhonetic(Phonetic instance);
    partial void UpdatePhonetic(Phonetic instance);
    partial void DeletePhonetic(Phonetic instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertWordsLessThan10(WordsLessThan10 instance);
    partial void UpdateWordsLessThan10(WordsLessThan10 instance);
    partial void DeleteWordsLessThan10(WordsLessThan10 instance);
    partial void InsertWordsLessThan11(WordsLessThan11 instance);
    partial void UpdateWordsLessThan11(WordsLessThan11 instance);
    partial void DeleteWordsLessThan11(WordsLessThan11 instance);
    partial void InsertWordsLessThan13(WordsLessThan13 instance);
    partial void UpdateWordsLessThan13(WordsLessThan13 instance);
    partial void DeleteWordsLessThan13(WordsLessThan13 instance);
    partial void InsertWordsLessThan7(WordsLessThan7 instance);
    partial void UpdateWordsLessThan7(WordsLessThan7 instance);
    partial void DeleteWordsLessThan7(WordsLessThan7 instance);
    partial void InsertWordsLessThan8(WordsLessThan8 instance);
    partial void UpdateWordsLessThan8(WordsLessThan8 instance);
    partial void DeleteWordsLessThan8(WordsLessThan8 instance);
    partial void InsertWordsLessThan9(WordsLessThan9 instance);
    partial void UpdateWordsLessThan9(WordsLessThan9 instance);
    partial void DeleteWordsLessThan9(WordsLessThan9 instance);
    #endregion
		
		public dbEngriskIsFunDataContext() : 
				base(global::EngriskIsFun.Properties.Settings.Default.EngriskIsFunConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public dbEngriskIsFunDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEngriskIsFunDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEngriskIsFunDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEngriskIsFunDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Definition> Definitions
		{
			get
			{
				return this.GetTable<Definition>();
			}
		}
		
		public System.Data.Linq.Table<WordsMoreThan13> WordsMoreThan13s
		{
			get
			{
				return this.GetTable<WordsMoreThan13>();
			}
		}
		
		public System.Data.Linq.Table<Phonetic> Phonetics
		{
			get
			{
				return this.GetTable<Phonetic>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan10> WordsLessThan10s
		{
			get
			{
				return this.GetTable<WordsLessThan10>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan11> WordsLessThan11s
		{
			get
			{
				return this.GetTable<WordsLessThan11>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan13> WordsLessThan13s
		{
			get
			{
				return this.GetTable<WordsLessThan13>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan7> WordsLessThan7s
		{
			get
			{
				return this.GetTable<WordsLessThan7>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan8> WordsLessThan8s
		{
			get
			{
				return this.GetTable<WordsLessThan8>();
			}
		}
		
		public System.Data.Linq.Table<WordsLessThan9> WordsLessThan9s
		{
			get
			{
				return this.GetTable<WordsLessThan9>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Definitions")]
	public partial class Definition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _DefinitionID;
		
		private string _PartOfSpeech;
		
		private string _Example;
		
		private long _WordID;
		
		private string _Text;
		
		private EntityRef<WordsMoreThan13> _WordsMoreThan13;
		
		private EntityRef<WordsLessThan10> _WordsLessThan10;
		
		private EntityRef<WordsLessThan11> _WordsLessThan11;
		
		private EntityRef<WordsLessThan13> _WordsLessThan13;
		
		private EntityRef<WordsLessThan7> _WordsLessThan7;
		
		private EntityRef<WordsLessThan8> _WordsLessThan8;
		
		private EntityRef<WordsLessThan9> _WordsLessThan9;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDefinitionIDChanging(long value);
    partial void OnDefinitionIDChanged();
    partial void OnPartOfSpeechChanging(string value);
    partial void OnPartOfSpeechChanged();
    partial void OnExampleChanging(string value);
    partial void OnExampleChanged();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public Definition()
		{
			this._WordsMoreThan13 = default(EntityRef<WordsMoreThan13>);
			this._WordsLessThan10 = default(EntityRef<WordsLessThan10>);
			this._WordsLessThan11 = default(EntityRef<WordsLessThan11>);
			this._WordsLessThan13 = default(EntityRef<WordsLessThan13>);
			this._WordsLessThan7 = default(EntityRef<WordsLessThan7>);
			this._WordsLessThan8 = default(EntityRef<WordsLessThan8>);
			this._WordsLessThan9 = default(EntityRef<WordsLessThan9>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefinitionID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this.OnDefinitionIDChanging(value);
					this.SendPropertyChanging();
					this._DefinitionID = value;
					this.SendPropertyChanged("DefinitionID");
					this.OnDefinitionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartOfSpeech", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PartOfSpeech
		{
			get
			{
				return this._PartOfSpeech;
			}
			set
			{
				if ((this._PartOfSpeech != value))
				{
					this.OnPartOfSpeechChanging(value);
					this.SendPropertyChanging();
					this._PartOfSpeech = value;
					this.SendPropertyChanged("PartOfSpeech");
					this.OnPartOfSpeechChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Example", DbType="NVarChar(500)")]
		public string Example
		{
			get
			{
				return this._Example;
			}
			set
			{
				if ((this._Example != value))
				{
					this.OnExampleChanging(value);
					this.SendPropertyChanging();
					this._Example = value;
					this.SendPropertyChanged("Example");
					this.OnExampleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", DbType="BigInt NOT NULL")]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					if (((((((this._WordsMoreThan13.HasLoadedOrAssignedValue || this._WordsLessThan10.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan11.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan13.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan7.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan8.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan9.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsMoreThan13_Definition", Storage="_WordsMoreThan13", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsMoreThan13 WordsMoreThan13
		{
			get
			{
				return this._WordsMoreThan13.Entity;
			}
			set
			{
				WordsMoreThan13 previousValue = this._WordsMoreThan13.Entity;
				if (((previousValue != value) 
							|| (this._WordsMoreThan13.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsMoreThan13.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsMoreThan13.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsMoreThan13");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan10_Definition", Storage="_WordsLessThan10", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan10 WordsLessThan10
		{
			get
			{
				return this._WordsLessThan10.Entity;
			}
			set
			{
				WordsLessThan10 previousValue = this._WordsLessThan10.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan10.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan10.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan10.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan10");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan11_Definition", Storage="_WordsLessThan11", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan11 WordsLessThan11
		{
			get
			{
				return this._WordsLessThan11.Entity;
			}
			set
			{
				WordsLessThan11 previousValue = this._WordsLessThan11.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan11.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan11.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan11.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan11");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan13_Definition", Storage="_WordsLessThan13", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan13 WordsLessThan13
		{
			get
			{
				return this._WordsLessThan13.Entity;
			}
			set
			{
				WordsLessThan13 previousValue = this._WordsLessThan13.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan13.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan13.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan13.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan13");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan7_Definition", Storage="_WordsLessThan7", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan7 WordsLessThan7
		{
			get
			{
				return this._WordsLessThan7.Entity;
			}
			set
			{
				WordsLessThan7 previousValue = this._WordsLessThan7.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan7.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan7.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan7.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan7");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan8_Definition", Storage="_WordsLessThan8", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan8 WordsLessThan8
		{
			get
			{
				return this._WordsLessThan8.Entity;
			}
			set
			{
				WordsLessThan8 previousValue = this._WordsLessThan8.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan8.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan8.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan9_Definition", Storage="_WordsLessThan9", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan9 WordsLessThan9
		{
			get
			{
				return this._WordsLessThan9.Entity;
			}
			set
			{
				WordsLessThan9 previousValue = this._WordsLessThan9.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan9.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan9.Entity = null;
						previousValue.Definitions.Remove(this);
					}
					this._WordsLessThan9.Entity = value;
					if ((value != null))
					{
						value.Definitions.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan9");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsMoreThan13")]
	public partial class WordsMoreThan13 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsMoreThan13()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsMoreThan13_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsMoreThan13_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsMoreThan13 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsMoreThan13 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsMoreThan13 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsMoreThan13 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phonetics")]
	public partial class Phonetic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PhoneticID;
		
		private string _Text;
		
		private string _Audio;
		
		private long _WordID;
		
		private EntityRef<WordsMoreThan13> _WordsMoreThan13;
		
		private EntityRef<WordsLessThan10> _WordsLessThan10;
		
		private EntityRef<WordsLessThan11> _WordsLessThan11;
		
		private EntityRef<WordsLessThan13> _WordsLessThan13;
		
		private EntityRef<WordsLessThan7> _WordsLessThan7;
		
		private EntityRef<WordsLessThan8> _WordsLessThan8;
		
		private EntityRef<WordsLessThan9> _WordsLessThan9;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhoneticIDChanging(long value);
    partial void OnPhoneticIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnAudioChanging(string value);
    partial void OnAudioChanged();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    #endregion
		
		public Phonetic()
		{
			this._WordsMoreThan13 = default(EntityRef<WordsMoreThan13>);
			this._WordsLessThan10 = default(EntityRef<WordsLessThan10>);
			this._WordsLessThan11 = default(EntityRef<WordsLessThan11>);
			this._WordsLessThan13 = default(EntityRef<WordsLessThan13>);
			this._WordsLessThan7 = default(EntityRef<WordsLessThan7>);
			this._WordsLessThan8 = default(EntityRef<WordsLessThan8>);
			this._WordsLessThan9 = default(EntityRef<WordsLessThan9>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneticID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PhoneticID
		{
			get
			{
				return this._PhoneticID;
			}
			set
			{
				if ((this._PhoneticID != value))
				{
					this.OnPhoneticIDChanging(value);
					this.SendPropertyChanging();
					this._PhoneticID = value;
					this.SendPropertyChanged("PhoneticID");
					this.OnPhoneticIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(500)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audio", DbType="NVarChar(500)")]
		public string Audio
		{
			get
			{
				return this._Audio;
			}
			set
			{
				if ((this._Audio != value))
				{
					this.OnAudioChanging(value);
					this.SendPropertyChanging();
					this._Audio = value;
					this.SendPropertyChanged("Audio");
					this.OnAudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", DbType="BigInt NOT NULL")]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					if (((((((this._WordsMoreThan13.HasLoadedOrAssignedValue || this._WordsLessThan10.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan11.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan13.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan7.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan8.HasLoadedOrAssignedValue) 
								|| this._WordsLessThan9.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsMoreThan13_Phonetic", Storage="_WordsMoreThan13", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsMoreThan13 WordsMoreThan13
		{
			get
			{
				return this._WordsMoreThan13.Entity;
			}
			set
			{
				WordsMoreThan13 previousValue = this._WordsMoreThan13.Entity;
				if (((previousValue != value) 
							|| (this._WordsMoreThan13.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsMoreThan13.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsMoreThan13.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsMoreThan13");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan10_Phonetic", Storage="_WordsLessThan10", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan10 WordsLessThan10
		{
			get
			{
				return this._WordsLessThan10.Entity;
			}
			set
			{
				WordsLessThan10 previousValue = this._WordsLessThan10.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan10.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan10.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan10.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan10");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan11_Phonetic", Storage="_WordsLessThan11", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan11 WordsLessThan11
		{
			get
			{
				return this._WordsLessThan11.Entity;
			}
			set
			{
				WordsLessThan11 previousValue = this._WordsLessThan11.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan11.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan11.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan11.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan11");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan13_Phonetic", Storage="_WordsLessThan13", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan13 WordsLessThan13
		{
			get
			{
				return this._WordsLessThan13.Entity;
			}
			set
			{
				WordsLessThan13 previousValue = this._WordsLessThan13.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan13.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan13.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan13.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan13");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan7_Phonetic", Storage="_WordsLessThan7", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan7 WordsLessThan7
		{
			get
			{
				return this._WordsLessThan7.Entity;
			}
			set
			{
				WordsLessThan7 previousValue = this._WordsLessThan7.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan7.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan7.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan7.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan7");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan8_Phonetic", Storage="_WordsLessThan8", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan8 WordsLessThan8
		{
			get
			{
				return this._WordsLessThan8.Entity;
			}
			set
			{
				WordsLessThan8 previousValue = this._WordsLessThan8.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan8.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan8.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan9_Phonetic", Storage="_WordsLessThan9", ThisKey="WordID", OtherKey="WordID", IsForeignKey=true)]
		public WordsLessThan9 WordsLessThan9
		{
			get
			{
				return this._WordsLessThan9.Entity;
			}
			set
			{
				WordsLessThan9 previousValue = this._WordsLessThan9.Entity;
				if (((previousValue != value) 
							|| (this._WordsLessThan9.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WordsLessThan9.Entity = null;
						previousValue.Phonetics.Remove(this);
					}
					this._WordsLessThan9.Entity = value;
					if ((value != null))
					{
						value.Phonetics.Add(this);
						this._WordID = value.WordID;
					}
					else
					{
						this._WordID = default(long);
					}
					this.SendPropertyChanged("WordsLessThan9");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UserID;
		
		private string _UserName;
		
		private string _Password;
		
		private int _Level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(long value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan10")]
	public partial class WordsLessThan10 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan10()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan10_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan10_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan10 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan10 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan10 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan10 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan11")]
	public partial class WordsLessThan11 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan11()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan11_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan11_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan11 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan11 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan11 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan11 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan13")]
	public partial class WordsLessThan13 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan13()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan13_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan13_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan13 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan13 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan13 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan13 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan7")]
	public partial class WordsLessThan7 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan7()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan7_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan7_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan7 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan7 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan7 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan7 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan8")]
	public partial class WordsLessThan8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan8()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan8_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan8_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan8 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan8 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan8 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WordsLessThan9")]
	public partial class WordsLessThan9 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _WordID;
		
		private string _Text;
		
		private EntitySet<Definition> _Definitions;
		
		private EntitySet<Phonetic> _Phonetics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordIDChanging(long value);
    partial void OnWordIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    #endregion
		
		public WordsLessThan9()
		{
			this._Definitions = new EntitySet<Definition>(new Action<Definition>(this.attach_Definitions), new Action<Definition>(this.detach_Definitions));
			this._Phonetics = new EntitySet<Phonetic>(new Action<Phonetic>(this.attach_Phonetics), new Action<Phonetic>(this.detach_Phonetics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WordID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long WordID
		{
			get
			{
				return this._WordID;
			}
			set
			{
				if ((this._WordID != value))
				{
					this.OnWordIDChanging(value);
					this.SendPropertyChanging();
					this._WordID = value;
					this.SendPropertyChanged("WordID");
					this.OnWordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan9_Definition", Storage="_Definitions", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Definition> Definitions
		{
			get
			{
				return this._Definitions;
			}
			set
			{
				this._Definitions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WordsLessThan9_Phonetic", Storage="_Phonetics", ThisKey="WordID", OtherKey="WordID")]
		public EntitySet<Phonetic> Phonetics
		{
			get
			{
				return this._Phonetics;
			}
			set
			{
				this._Phonetics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan9 = this;
		}
		
		private void detach_Definitions(Definition entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan9 = null;
		}
		
		private void attach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan9 = this;
		}
		
		private void detach_Phonetics(Phonetic entity)
		{
			this.SendPropertyChanging();
			entity.WordsLessThan9 = null;
		}
	}
}
#pragma warning restore 1591
